[program:netbird]
command=netbird up --setup-key ${NETBIRD_SETUP_KEY} --management-url ${NB_MANAGEMENT_URL}
autorestart=true
priority=30
stdout_logfile=/var/log/supervisor/netbird.log
stderr_logfile=/var/log/supervisor/netbird.log