[program:netbird]
command=netbird up --setup-key %(ENV_NETBIRD_SETUP_KEY)s --management-url %(ENV_NB_MANAGEMENT_URL)s
autorestart=true
priority=30
stdout_logfile=/var/log/supervisor/netbird.log
stderr_logfile=/var/log/supervisor/netbird.log