[program:netbird]
command=netbird up --foreground-mode --setup-key %(ENV_NB_SETUP_KEY)s --management-url %(ENV_NB_MANAGEMENT_URL)s --allow-server-ssh --enable-ssh-root;\
autorestart=true
autostart=true
startsecs=10
priority=99
stdout_logfile=/var/log/supervisor/netbird.log
stderr_logfile=/var/log/supervisor/netbird.log
stopsignal=TERM